*** Settings ***

# Libs
Resource    ../resources/Config/Libs.resource

# Hooks
Resource    ../resources/Hooks/Hooks.resource

# Page Resource
Resource    ../resources/Pages/HomePage.resource
Resource    ../resources/Pages/ProductDetails.resource
Resource    ../resources/Pages/CheckoutPage.resource
Resource    ../resources/Pages/RegisterPage.resource

# Locators
Resource    ../resources/locators/RegisterLocators.resource
Resource    ../resources/locators/LoginLocators.resource